version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - mkdir dist
      - npm install -g yarn
      - yarn install
      - echo yarn -v
      - yarn -v
  build:
    commands:
      - yarn run build
  post_build:
    commands:
      - tar cf /tmp/node_modules.tar node_modules
artifacts:
  files:
    - 'dist/*'
